name: Build
on: [workflow_dispatch, pull_request, push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache packages
        uses: actions/cache@v3
        id: packages-cache
        with:
          path: |
            ~/Library/Developer/Xcode/DerivedData/Example*/Build
            ~/Library/Developer/Xcode/DerivedData/Example*/SourcePackages
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-
      - name: Build
        run: fastlane build
        env:
          HAS_PACKAGES_CACHE_HIT: ${{ steps.packages-cache.outputs.cache-hit == 'true' }}
