name: Build
on: [workflow_dispatch, pull_request, push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: irgaly/xcode-cache@v1
        id: xcode-cache
        with:
          key: xcode-cache-deriveddata-${{ github.workflow }}-${{ github.sha }}
          restore-keys: xcode-cache-deriveddata-${{ github.workflow }}-
      - name: Build
        run: fastlane build
        env:
          HAS_PACKAGES_CACHE_HIT: ${{ steps.xcode-cache.outputs.swiftpm-restored == 'true' }}
